### ISSUE TITLE
[Polish Needed] Task List Inconsistency

### ISSUE THREAD

**Issue by mmjiang-ucsd** [nickkro25/cse112_team15#14]
**Describe Issue**
The top right corner of the task list is sharp while the other 3 corners are rounded.

**Additional Documentation**
![image](https://user-images.githubusercontent.com/74376151/167760144-7092cda6-8d8f-4ec6-84c6-d5c9c5e11ef4.png)

**Comment by jcpriyanto** [comment]
![image](https://user-images.githubusercontent.com/76898754/169915370-7df0124c-b451-46b5-8922-393ab53d45b4.png)

I believe this  is due to the weird implementation of how the container of the table works. So this might take more time.

**Comment by jcpriyanto** [comment]
Sticked to the squared off design.
