### ISSUE TITLE
[Bug Report] Task input doesn't work on iOS

### ISSUE THREAD

**Issue by AW0723** [nickkro25/cse112_team15#179]
**Describe Bug**
The app shows invalid input even though the input should be valid.

**Steps to recreate the issue**
- Open our app on iOS, put anything in the task and # of pomos
- Click plus sign to add the task
- Invalid input shows up

**Additional Documentation**
![image](https://user-images.githubusercontent.com/64997746/172072369-2e11edeb-993a-49b4-82d3-6528c3943dd0.png)

**Comment by yiw008** [comment]
It doesn't work in Safari either.

**Comment by TheOneGeo** [comment]
The quickest fix seems to be this [polyfill](https://github.com/ungap/custom-elements#readme). I have a fix working on bugfix/ios_tasklist
