### ISSUE TITLE
[Polish Needed] CSS Validation Fails

### ISSUE THREAD

**Issue by mmjiang-ucsd** [nickkro25/cse112_team15#26]
**Describe Issue**
Using https://jigsaw.w3.org/css-validator/, our app fails the validator with 3 errors that should be fixed. There are also 134 warnings, but those seem to be due to vendor extensions.

**Additional Documentation**
A PDF of the results can be found in `docs\measurables`.

**Comment by AW0723** [comment]
There are more errors after new things are added
