### ISSUE TITLE
[FEATURE REQ] Timer auto-start toggle option

### ISSUE THREAD

**Issue by mmjiang-ucsd** [nickkro25/cse112_team15#34]
**Describe Feature**
Currently, the timer will automatically transition straight into the next phase when the current phase ends. It would be nice to have the option to let the user choose if the timer automatically transitions or not.

**Why is this useful**
More power to the user, more customizability

**Additional Requirements**
N/A

**Comment by AW0723** [comment]
What did u envision this feature to look like?
I was thinking after auto-start is turned off, when a pomo session ends, the end day button turns into start, and then the user can start the break when desired. Is this more or less what u were thinking?
