### ISSUE TITLE
[Bug Report]Secret Token not found in CD

### ISSUE THREAD

**Issue by w1lai** [nickkro25/cse112_team15#43]
**Describe Bug**
`CD.yml` cannot pick up git hub secret token
page-deployment can pick up and build updated URL

**Steps to recreate the issue**
On push to main, github runs CD.yml 

**Additional Documentation**
Check `CD.yml` user, might have related to the owner of repo changed?

**Comment by nickkro25** [comment]
For steps to recreate the issue, you say on a push to main, github runs CD.yml. Why are we pushing to main? Shouldn't it be a separate branch that is being pushed to and then making a PR to merge them?
