### ISSUE TITLE
[Polish Needed] Wonky night mode transitions and colors

### ISSUE THREAD

**Issue by mmjiang-ucsd** [nickkro25/cse112_team15#54]
**Describe Issue**
- Navbar doesn't transition smoothly, becomes the same color as the overall background
- Tasklist also doesn't transition smoothly, background behind task input becomes the same color as the overall background

**Additional Documentation**
![dark_mode_transition](https://user-images.githubusercontent.com/74376151/169145489-59e8e671-79d8-417d-a3df-5cb250b5caae.gif)

**Comment by w1lai** [comment]
additional bug on night mode
the options for the soundboard settings are not visible (both work time and break time sound)
![image](https://user-images.githubusercontent.com/78565740/169923378-78a509d8-e8e7-45aa-8ce9-2f88fb5e5f3e.png)
