### ISSUE TITLE
[Bug Report] Custom timer length setting not showing correctly in dark mode

### ISSUE THREAD

**Issue by AW0723** [nickkro25/cse112_team15#58]
**Describe Bug**
The custom timer lengths setting doesn't show correctly in dark mode.

**Steps to recreate the issue**
- Turn on dark mode

**Additional Documentation**
Add any pictures/gifs as necessary to demonstrate
![image](https://user-images.githubusercontent.com/64997746/169180341-23d2a573-a0f1-496e-b6a6-5f83e69990c3.png)

**Comment by efloresCSE** [comment]
Was nuked in latest commit, will reupload code again
