### ISSUE TITLE
[Bug Report] Timer flickers when timer length is changed

### ISSUE THREAD

**Issue by AW0723** [nickkro25/cse112_team15#59]
**Describe Bug**
After the countdown is started, when the user change the timer length, the timer display flickers

**Steps to recreate the issue**
- Start the timer
- Open settings
- Change timer length

**Additional Documentation**
Add any pictures/gifs as necessary to demonstrate

**Comment by efloresCSE** [comment]
We plan to have everything hidden when pomo is running, so this issue will be resolved then.
