### ISSUE TITLE
[Polish Needed] Save custom timer lengths in localStorage

### ISSUE THREAD

**Issue by AW0723** [nickkro25/cse112_team15#63]
**Describe Issue**
The timer lengths aren't saved, so refreshing the page would delete user settings

**Additional Documentation**
Add any pictures/gifs as necessary to demonstrate

**Comment by efloresCSE** [comment]
Can we get more clarification? I type 10 in focus, click away + refresh and it saves the timer length. Same for short and long breaks.

**Comment by AW0723** [comment]
Sorry, I made a mistake D:

**Comment by efloresCSE** [comment]
np np :)
