### ISSUE TITLE
[Bug Report] Background Timer Bug

### ISSUE THREAD

**Issue by AW0723** [nickkro25/cse112_team15#7]
**Describe Bug**
When the web app is not focused, the timer noticeably slows down.

**Steps to recreate the issue**
- Start the timer
- Select another browser tab
- The timer in the title should slow down

**Comment by PabloGratas** [comment]
Since this is the only issue that's a bug and not a feature request, I think this one should be top priority. I have a lot of assignments due on Wednesday, but I should be able to get this bug fixed by the end of the weekend as long as I'm not underestimating the difficulty involved.

**Comment by mmjiang-ucsd** [comment]
Fixing this bug means migrating the timer functionality over to web workers, which _could_ be a good amount of effort
